# Generated by Django 5.1.6 on 2025-03-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
