# Generated by Django 5.1.6 on 2025-03-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='audio',
            field=models.FileField(null=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='podcast',
            name='transcript',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
