# Generated by Django 5.1.6 on 2025-03-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_search', '0002_podcast_audio_podcast_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
