# Generated by Django 5.1.6 on 2025-04-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_search', '0003_alter_podcast_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='earnings',
            field=models.BigIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcast',
            name='views',
            field=models.BigIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
