# Generated by Django 5.1.6 on 2025-04-06 11:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_search', '0003_alter_podcast_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
