# Generated by Django 5.1.6 on 2025-04-06 11:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_search', '0004_podcast_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='id',
        ),
        migrations.AlterField(
            model_name='podcast',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
