# Generated by Django 5.1.6 on 2025-04-10 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_search', '0004_podcast_earnings_podcast_views'),
        ('user_management', '0005_alter_creatormodel_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='podcast_creator', to='user_management.creatormodel'),
        ),
    ]
