# Generated by Django 5.1.6 on 2025-04-06 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_search', '0005_remove_podcast_id_alter_podcast_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='uuid',
            new_name='id',
        ),
    ]
