# Generated by Django 5.1.6 on 2025-04-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_search', '0006_rename_uuid_podcast_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='episode',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='episode'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='episodeNumber',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
