# Generated by Django 5.1.6 on 2025-04-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_search', '0007_podcast_episode_podcast_episodenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
