# Generated by Django 5.1.6 on 2025-04-09 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_search', '0008_podcast_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='public',
            new_name='is_public',
        ),
    ]
