# Generated by Django 5.1.6 on 2025-04-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_search', '0009_rename_public_podcast_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='episodeNumber',
            new_name='episode_number',
        ),
    ]
