# Generated by Django 5.1.6 on 2025-04-11 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_search', '0005_podcast_creator'),
        ('podcast_search', '0011_alter_podcast_description_alter_podcast_transcript'),
    ]

    operations = [
    ]
