# Generated by Django 5.1.6 on 2025-04-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_search', '0012_merge_20250411_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='earnings',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
    ]
