# Generated by Django 5.1.6 on 2025-04-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_listenermodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatormodel',
            name='staff',
            field=models.TextField(blank=True, null=True),
        ),
    ]
