# Generated by Django 5.1.6 on 2025-04-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_alter_creatormodel_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatormodel',
            name='staff',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
