# Generated by Django 5.1.6 on 2025-04-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_alter_creatormodel_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='followers',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
