# Generated by Django 5.1.6 on 2025-04-11 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_usermodel_followers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creatormodel',
            options={'verbose_name': 'creator', 'verbose_name_plural': 'creators'},
        ),
        migrations.AlterModelOptions(
            name='listenermodel',
            options={'verbose_name': 'listener', 'verbose_name_plural': 'listeners'},
        ),
        migrations.RemoveField(
            model_name='creatormodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='creatormodel',
            name='creator_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='creator', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listenermodel',
            name='follows',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follows', to='user_management.creatormodel'),
        ),
    ]
