# Generated by Django 5.1.6 on 2025-04-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0007_alter_creatormodel_options_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="listenermodel",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="listenermodel",
            name="usermodel_ptr",
        ),
        migrations.AddField(
            model_name="listenermodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, serialize=False, verbose_name="ID"
            ),
            preserve_default=False,
        ),
    ]
