# Generated by Django 5.1.6 on 2025-04-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_alter_listenermodel_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listenermodel',
            name='follows',
        ),
        migrations.AddField(
            model_name='listenermodel',
            name='follows',
            field=models.ManyToManyField(blank=True, null=True, related_name='follows', to='user_management.creatormodel'),
        ),
    ]
