# Generated by Django 5.1.6 on 2025-04-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_remove_listenermodel_follows_listenermodel_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listenermodel',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='follows', to='user_management.creatormodel'),
        ),
    ]
