# Generated by Django 5.1.6 on 2025-04-21 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_alter_listenermodel_follows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listenermodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='listenermodel',
            name='listener_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='listener', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
