# Generated by Django 5.0.2 on 2025-03-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_share', '0001_initial'),
    ]

    operations = [
    ]
