# Generated by Django 5.0.2 on 2025-03-21 13:31
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_share', '0002_auto_20250321_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedpodcast',
            name='share_link',
        ),
        migrations.AddField(
            model_name='sharedpodcast',
            name='share_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
