# Generated by Django 5.1.6 on 2025-04-06 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_share', '0003_remove_sharedpodcast_share_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedpodcast',
            name='share_uuid',
        ),
    ]
